# Generated by Django 4.1.7 on 2023-03-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_tasks_is_deleted_alter_tasks_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
