# Generated by Django 4.1.7 on 2023-04-15 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_tasks_is_deleted_project_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_deleted',
        ),
    ]
